version: '3.8'
services:
  rdesktop:
    image: localhost/linuxserver-rdesktop-xfce-python-and-tools:1.0
    container_name: linuxserver-rdesktop-xfce-python-and-tools
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - $PWD/home:/config
    ports:
      - 3350:3350
      - 3389:3389
    shm_size: "4gb"
    restart: unless-stopped
